name: halo_browser
description: A lightning-fast, privacy-focused, and cross-platform web browser
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_rust_bridge: ^1.82.4
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  provider: ^6.1.1
  flutter_inappwebview: ^5.8.0
  window_manager: ^0.3.8
  flutter_acrylic: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  flutter_rust_bridge_codegen: ^1.82.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 